### ISSUE TITLE
Surface had no valid native window. on barcodeView.start()

### ISSUE THREAD

**Issue by OmarJoya** [brightec/KBarcode#13] opened 2019-04-29 20:18 UTC
Once I grant the CAMERA permissions barcodeView.start() throws an error

On Android Marshmallow is not needed call to start but on Android Pie

I want to know if there is a way to know if the barcode is already started to avoid calling .start()

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.centinal.ivs.internal.debug, PID: 17159
    java.lang.IllegalArgumentException: Surface was abandoned
        at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:70)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:97)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:71)
        at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:474)
        at uk.co.brightec.kbarcode.camera.Camera2Source.createCaptureSession$kbarcode_release(Camera2Source.kt:121)
        at uk.co.brightec.kbarcode.camera.Camera2Source$start$1.onOpened(Camera2Source.kt:55)
        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:134)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: android.hardware.camera2.legacy.LegacyExceptionUtils$BufferQueueAbandonedException
        at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnError(LegacyExceptionUtils.java:64)
        at android.hardware.camera2.legacy.LegacyCameraDevice.getSurfaceSize(LegacyCameraDevice.java:540)
        at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:68)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:97) 
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:71) 
        at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:474) 
        at uk.co.brightec.kbarcode.camera.Camera2Source.createCaptureSession$kbarcode_release(Camera2Source.kt:121) 
        at uk.co.brightec.kbarcode.camera.Camera2Source$start$1.onOpened(Camera2Source.kt:55) 
        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:134) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by alistairsykes** [comment] 2019-05-08 12:32
Hi @OmarJoya . Thanks for reporting this, to clarify these are your steps to recreate:
- Be on Android 6 device
- Open app
- Request permission
- Once granted call barcode.start()

Is that correct?

**Comment by OmarJoya** [comment] 2019-05-08 14:40
Yes, also I added the BarcodeView as an observer to the lifecycle in onActivityCreated as you have on https://github.com/brightec/KBarcode/wiki

![image](https://user-images.githubusercontent.com/11036913/57383920-425cc880-7175-11e9-98fe-37f65506b957.png)

**Comment by alistairsykes** [comment] 2019-05-08 16:03
This exception does appear to be caused by affectively calling `barcodeView.start()` twice, in quick succession.

I had previously thought the library handled calling `start()` twice, as seen in `BarcodeScanner.start()` where I check if the `cameraSource.isStarted()`. However if you call twice in quick succession, the second time the camera source does not report as starting because it is still opening the camera.

I will create a pull request soon which will address this issue.

For your case @OmarJoya, you are right that marshmallow is the differing factor. It appears that permissions dialogs behave differently between M and Q (not sure exactly for each version in between). On M the permissions dialog causes `@OnLifecycleEvent(Lifecycle.Event.ON_START)` to be called when it dismisses. On Q it does not.
A temporary work around while I get this pull request together, would be to do a version check before calling `barcodeView.start()` after the permission is granted.

**Comment by alistairsykes** [comment] 2019-05-09 08:28
Pull request has been approved and merged.

**Comment by OmarJoya** [comment] 2019-05-09 15:21
does this last merge contain the fix?, I'm now using the kbarcode version 1.0.2, but seems the problem is not solved

**Comment by alistairsykes** [comment] 2019-05-09 15:24
We are yet to do a release with this fix in. We had a few other things to get done before publishing the code. I will post again on this issue once we have done that.

**Comment by alistairsykes** [comment] 2019-05-10 08:22
We have now done a release which includes this fix.

https://github.com/brightec/KBarcode/releases/tag/v1.0.3

**Closed as completed by alistairsykes** 2019-05-10 08:22 UTC
Labels: bug
